CREATE TABLE wtl.cities (
    city_id INT NOT NULL GENERATED ALWAYS AS IDENTITY
    , city_name VARCHAR NOT NULL
    , country VARCHAR NOT NULL
)

INSERT INTO wtl.cities (city_name, country)
VALUES
('Shanghai', 'China')
, ('BEIJING', 'China')
, ('Karachi', 'Pakistan')
, ('Istanbul', 'Turkey')
, ('DHAKA', 'Bangladesh')
, ('TOKYO', 'Japan')
, ('MOSCOW', 'Russia')
, ('MANILA', 'Philippines')
, ('Tianjin', 'China')
, ('Mumbai (Bombay)', 'India')
, ('Sao Paulo', 'Brazil')
, ('Shenzhen', 'China')
, ('Guangzhou', 'China')
, ('DELHI', 'India')
, ('Wuhan', 'China')
, ('Lahore', 'Pakistan')
, ('Seoul', 'South Korea')
, ('Chengdu', 'China')
, ('KINSHASA', 'Congo D.R.')
, ('LIMA', 'Peru')
, ('JAKARTA', 'Indonesia')
, ('CAIRO', 'Egypt')
, ('MEXICO CITY', 'Mexico')
, ('TEHRAN', 'Iran')
, ('BAGHDAD', 'Iraq')
, ('Xian', 'China')
, ('LONDON', 'UK')
, ('New York City', 'USA')
, ('Nanjing', 'China')
, ('Bangalore', 'India')
, ('Ho Chi Minh City', 'Vietnam')
, ('BANGKOK', 'Thailand')
, ('Chongquin', 'China')
, ('BOGOTA', 'Colombia')
, ('Lagos', 'Nigeria')
, ('RIYADH', 'Saudi Arabia')
, ('Hong Kong', 'China')
, ('Chennai', 'India')
, ('Hangzhou', 'China')
, ('Hyderabad', 'India')
, ('Rio de Janeiro', 'Brazil')
, ('Zhengzhou', 'China')
, ('Shenyang', 'China')
, ('Qingdao', 'China')
, ('SANTIAGO', 'Chile')
, ('Dalian', 'China')
, ('SINGAPORE', 'Singapore')
, ('Ahmadabad', 'India')
, ('Suzhou', 'China')
, ('St Petersburg', 'Russia')